const CONFERENCES = [
  {
    id: "m2020-eu-2026",
    name: "Money20/20 Europe",
    startDate: "2026-06-02",
    endDate: "2026-06-04",
    city: "Amsterdam",
    country: "Netherlands",
    region: "Europe",
    verticals: ["Payments", "Fintech", "Banking", "Embedded Finance"],
    audience: 7400,
    seniority: 5,
    buyerDensity: 5,
    fxRelevance: 5,
    travelRelevance: 2,
    pspRelevance: 5,
    costTier: 4,
    status: "Committed",
    owner: "Maya",
    source: "https://europe.money2020.com/attend"
  },
  {
    id: "phocuswright-eu-2026",
    name: "Phocuswright Europe",
    startDate: "2026-06-15",
    endDate: "2026-06-17",
    city: "Barcelona",
    country: "Spain",
    region: "Europe",
    verticals: ["Travel", "Travel Tech", "Wholesalers"],
    audience: 1200,
    seniority: 4,
    buyerDensity: 4,
    fxRelevance: 4,
    travelRelevance: 5,
    pspRelevance: 2,
    costTier: 3,
    status: "Considering",
    owner: "Noah",
    source: "https://www.phocuswrighteurope.com/Attend"
  },
  {
    id: "seamless-me-2026",
    name: "Seamless Fintech Middle East",
    startDate: "2026-09-22",
    endDate: "2026-09-24",
    city: "Dubai",
    country: "UAE",
    region: "Middle East",
    verticals: ["Payments", "Fintech", "Ecommerce", "Banking"],
    audience: 25000,
    seniority: 4,
    buyerDensity: 4,
    fxRelevance: 4,
    travelRelevance: 2,
    pspRelevance: 5,
    costTier: 3,
    status: "Considering",
    owner: "Unassigned",
    source: "https://www.terrapinn.com/exhibition/seamless-middle-east-fintech"
  },
  {
    id: "sff-2026",
    name: "Singapore FinTech Festival",
    startDate: "2026-11-18",
    endDate: "2026-11-20",
    city: "Singapore",
    country: "Singapore",
    region: "APAC",
    verticals: ["Fintech", "Payments", "Banking", "RegTech"],
    audience: 60000,
    seniority: 4,
    buyerDensity: 4,
    fxRelevance: 4,
    travelRelevance: 2,
    pspRelevance: 4,
    costTier: 5,
    status: "Watchlist",
    owner: "Unassigned",
    source: "https://www.fintechfestival.sg/"
  },
  {
    id: "money2020-usa-2026",
    name: "Money20/20 USA",
    startDate: "2026-10-18",
    endDate: "2026-10-21",
    city: "Las Vegas",
    country: "USA",
    region: "North America",
    verticals: ["Payments", "Fintech", "Banking", "Retail"],
    audience: 11000,
    seniority: 5,
    buyerDensity: 5,
    fxRelevance: 4,
    travelRelevance: 2,
    pspRelevance: 5,
    costTier: 5,
    status: "Committed",
    owner: "Lior",
    source: "https://us.money2020.com/"
  },
  {
    id: "finovate-europe-2026",
    name: "FinovateEurope",
    startDate: "2026-02-24",
    endDate: "2026-02-25",
    city: "London",
    country: "UK",
    region: "Europe",
    verticals: ["Fintech", "Banking", "SaaS"],
    audience: 1000,
    seniority: 4,
    buyerDensity: 3,
    fxRelevance: 3,
    travelRelevance: 1,
    pspRelevance: 3,
    costTier: 2,
    status: "Watchlist",
    owner: "Unassigned",
    source: "https://informaconnect.com/finovateeurope/"
  },
  {
    id: "merchant-risk-council-vegas-2026",
    name: "MRC Vegas",
    startDate: "2026-03-09",
    endDate: "2026-03-12",
    city: "Las Vegas",
    country: "USA",
    region: "North America",
    verticals: ["Payments", "Fraud", "Ecommerce", "Merchants"],
    audience: 1800,
    seniority: 4,
    buyerDensity: 4,
    fxRelevance: 4,
    travelRelevance: 1,
    pspRelevance: 5,
    costTier: 3,
    status: "Considering",
    owner: "Lior",
    source: "https://merchantriskcouncil.org/events"
  },
  {
    id: "travel-tech-show-2026",
    name: "TravelTech Show",
    startDate: "2026-06-24",
    endDate: "2026-06-25",
    city: "London",
    country: "UK",
    region: "Europe",
    verticals: ["Travel", "Travel Tech", "SaaS"],
    audience: 4000,
    seniority: 3,
    buyerDensity: 3,
    fxRelevance: 4,
    travelRelevance: 5,
    pspRelevance: 2,
    costTier: 2,
    status: "Considering",
    owner: "Noah",
    source: "https://traveltech-show.com/"
  },
  {
    id: "itb-berlin-2026",
    name: "ITB Berlin",
    startDate: "2026-03-03",
    endDate: "2026-03-05",
    city: "Berlin",
    country: "Germany",
    region: "Europe",
    verticals: ["Travel", "Tourism", "Wholesalers"],
    audience: 24000,
    seniority: 3,
    buyerDensity: 3,
    fxRelevance: 4,
    travelRelevance: 5,
    pspRelevance: 1,
    costTier: 4,
    status: "Watchlist",
    owner: "Unassigned",
    source: "https://www.itb.com/"
  },
  {
    id: "global-fintech-fest-2026",
    name: "Global Fintech Fest",
    startDate: "2026-10-07",
    endDate: "2026-10-09",
    city: "Mumbai",
    country: "India",
    region: "APAC",
    verticals: ["Fintech", "Payments", "Banking", "Policy"],
    audience: 80000,
    seniority: 4,
    buyerDensity: 4,
    fxRelevance: 4,
    travelRelevance: 1,
    pspRelevance: 5,
    costTier: 4,
    status: "Watchlist",
    owner: "Unassigned",
    source: "https://globalfintechfest.com/"
  },
  {
    id: "payments-leaders-summit-eu-2026",
    name: "Payments Leaders' Summit Europe",
    startDate: "2026-04-21",
    endDate: "2026-04-22",
    city: "London",
    country: "UK",
    region: "Europe",
    verticals: ["Payments", "Merchants", "Banking"],
    audience: 700,
    seniority: 5,
    buyerDensity: 5,
    fxRelevance: 5,
    travelRelevance: 1,
    pspRelevance: 5,
    costTier: 2,
    status: "Committed",
    owner: "Maya",
    source: "https://www.paymentsleaderssummit.com/"
  },
  {
    id: "travel-payments-summit-2026",
    name: "Airline & Travel Payments Summit",
    startDate: "2026-05-12",
    endDate: "2026-05-14",
    city: "London",
    country: "UK",
    region: "Europe",
    verticals: ["Travel", "Payments", "Airlines"],
    audience: 600,
    seniority: 4,
    buyerDensity: 4,
    fxRelevance: 5,
    travelRelevance: 5,
    pspRelevance: 4,
    costTier: 2,
    status: "Considering",
    owner: "Noah",
    source: "https://www.airlineinformation.org/events"
  }
];

const LEADS = [
  {
    id: "lead-1",
    conferenceId: "m2020-eu-2026",
    firstName: "Priya",
    lastName: "Raman",
    company: "PayBridge",
    title: "VP Partnerships",
    email: "priya.raman@paybridge.example",
    phone: "",
    vertical: "Payments",
    urgency: "This quarter",
    notes: "Handles cross-border merchant settlement. Asked about reducing FX slippage on weekend processing.",
    sentiment: "Strong",
    nextStep: "Send PSP treasury one-pager",
    createdAt: "2026-06-02T10:20:00.000Z"
  },
  {
    id: "lead-2",
    conferenceId: "payments-leaders-summit-eu-2026",
    firstName: "Priya",
    lastName: "Raman",
    company: "PayBridge",
    title: "Director of Strategic Partnerships",
    email: "priya.raman@paybridge.example",
    phone: "",
    vertical: "Payments",
    urgency: "This quarter",
    notes: "Remembered Grain from Money20/20 prep emails. Newly owns PSP treasury vendor shortlist.",
    sentiment: "Strong",
    nextStep: "Book 30 min with CFO and treasury lead",
    createdAt: "2026-04-21T15:45:00.000Z"
  },
  {
    id: "lead-3",
    conferenceId: "phocuswright-eu-2026",
    firstName: "Jon",
    lastName: "Muller",
    company: "RoomRiver",
    title: "Commercial Director",
    email: "jon.muller@roomriver.example",
    phone: "",
    vertical: "Travel",
    urgency: "Exploring",
    notes: "Travel wholesaler with EUR/USD exposure. Curious but budget not approved.",
    sentiment: "Medium",
    nextStep: "Invite to July travel FX webinar",
    createdAt: "2026-06-15T12:10:00.000Z"
  },
  {
    id: "lead-4",
    conferenceId: "travel-payments-summit-2026",
    firstName: "Jonathan",
    lastName: "Mueller",
    company: "RoomRiver",
    title: "Commercial Director",
    email: "",
    phone: "",
    vertical: "Travel",
    urgency: "Exploring",
    notes: "Same travel wholesaler use case. Keeps asking for benchmarks, no project owner yet.",
    sentiment: "Medium",
    nextStep: "Qualify budget owner before next follow-up",
    createdAt: "2026-05-13T09:15:00.000Z"
  },
  {
    id: "lead-5",
    conferenceId: "seamless-me-2026",
    firstName: "Noura",
    lastName: "Al-Hassan",
    company: "DesertPay",
    title: "Head of Treasury",
    email: "noura@desertpay.example",
    phone: "",
    vertical: "Payments",
    urgency: "Immediate",
    notes: "Wants API-based hedging for merchant payouts in GCC and Europe.",
    sentiment: "Strong",
    nextStep: "Send HubSpot intro to solutions engineering",
    createdAt: "2026-09-22T14:25:00.000Z"
  }
];
